version: 0.2
phases:
  install:
    runtime-versions:
     nodejs: 14.x
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on 'date'
# Include only the files required for your application to run.
artifacts:
  files:
    - public/**/*
    - build/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - buildspec.yml